--
-- PostgreSQL database dump
--

\restrict gMOkOVw60OCwDnlSerQh0doQvB1TKwAbhmpWaMUbrYqWETuTmrMM40947mU2fjW

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments (
    appointment_id integer NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    room_id integer,
    appointment_date date NOT NULL,
    appointment_time time without time zone NOT NULL,
    reason text,
    diagnosis text,
    status character varying(30) DEFAULT 'Scheduled'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.appointments OWNER TO postgres;

--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments ALTER COLUMN appointment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    department_id integer NOT NULL,
    department_name character varying(100) NOT NULL,
    description text,
    phone character varying(20)
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: departments_department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.departments_department_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.departments_department_id_seq OWNER TO postgres;

--
-- Name: departments_department_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.departments_department_id_seq OWNED BY public.departments.department_id;


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctors (
    doctor_id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    specialization character varying(100),
    phone character varying(20),
    email character varying(100),
    department_id integer,
    status character varying(30) DEFAULT 'Active'::character varying
);


ALTER TABLE public.doctors OWNER TO postgres;

--
-- Name: doctors_doctor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.doctors ALTER COLUMN doctor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_doctor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_medicines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_medicines (
    id integer NOT NULL,
    invoice_id integer NOT NULL,
    medicine_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    subtotal numeric(15,2) NOT NULL
);


ALTER TABLE public.invoice_medicines OWNER TO postgres;

--
-- Name: invoice_medicines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_medicines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_medicines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices (
    invoice_id integer NOT NULL,
    appointment_id integer NOT NULL,
    issue_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    examination_fee numeric(12,2) DEFAULT 0,
    medicine_fee numeric(12,2) DEFAULT 0,
    total_amount numeric(15,2) DEFAULT 0,
    payment_status character varying(30) DEFAULT 'Unpaid'::character varying
);


ALTER TABLE public.invoices OWNER TO postgres;

--
-- Name: invoices_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoices ALTER COLUMN invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medicines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medicines (
    medicine_id integer NOT NULL,
    medicine_name character varying(150) NOT NULL,
    unit character varying(30),
    price numeric(12,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    description text
);


ALTER TABLE public.medicines OWNER TO postgres;

--
-- Name: medicines_medicine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medicines ALTER COLUMN medicine_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medicines_medicine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients (
    patient_id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    date_of_birth date,
    gender character varying(10),
    phone character varying(20),
    email character varying(100),
    address text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.patients OWNER TO postgres;

--
-- Name: patients_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patients ALTER COLUMN patient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms (
    room_id integer NOT NULL,
    room_number character varying(20) NOT NULL,
    room_type character varying(50),
    department_id integer,
    status character varying(30) DEFAULT 'Available'::character varying
);


ALTER TABLE public.rooms OWNER TO postgres;

--
-- Name: rooms_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments department_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments ALTER COLUMN department_id SET DEFAULT nextval('public.departments_department_id_seq'::regclass);


--
-- Data for Name: appointments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments (appointment_id, patient_id, doctor_id, room_id, appointment_date, appointment_time, reason, diagnosis, status, created_at) FROM stdin;
1	1	1	1	2026-07-15	08:00:00	Đau ngực khi gắng sức	Thiếu máu cơ tim	Completed	2026-08-17 00:38:09.429553
2	2	2	2	2026-07-15	09:30:00	Hồi hộp, đánh trống ngực	Loạn nhịp tim	Completed	2026-08-17 00:38:09.429553
3	3	3	3	2026-07-16	08:30:00	Đau đầu dữ dội	Migraine	Scheduled	2026-08-17 00:38:09.429553
4	4	4	4	2026-07-16	10:00:00	Chóng mặt, mất thăng bằng	Rối loạn tiền đình	Completed	2026-08-17 00:38:09.429553
5	5	5	5	2026-07-17	09:00:00	Đau gối sau chấn thương	Rách dây chằng	Cancelled	2026-08-17 00:38:09.429553
6	6	6	6	2026-07-17	10:30:00	Đau lưng mãn tính	Thoái hóa cột sống	Completed	2026-08-17 00:38:09.429553
7	7	7	7	2026-07-18	08:00:00	Sốt cao 39.5°C	Viêm họng cấp	Completed	2026-08-17 00:38:09.429553
8	8	8	8	2026-07-18	09:30:00	Chán ăn, sụt cân	Suy dinh dưỡng	Scheduled	2026-08-17 00:38:09.429553
9	9	9	9	2026-07-19	10:00:00	Phát ban toàn thân ngứa	Dị ứng thuốc	Completed	2026-08-17 00:38:09.429553
10	10	10	10	2026-07-19	11:00:00	Mụn trứng cá nhiều	Mụn viêm	Scheduled	2026-08-17 00:38:09.429553
11	11	11	11	2026-07-20	08:30:00	Đau bụng vùng thượng vị	Viêm loét dạ dày	Completed	2026-08-17 00:38:09.429553
12	12	12	12	2026-07-20	09:45:00	Khát nước, đi tiểu nhiều	Đái tháo đường type 2	Completed	2026-08-17 00:38:09.429553
13	13	13	13	2026-07-21	10:30:00	Ù tai, nghe kém	Viêm tai giữa	Scheduled	2026-08-17 00:38:09.429553
14	14	14	14	2026-07-21	11:15:00	Chảy dịch mũi xanh	Viêm xoang	Completed	2026-08-17 00:38:09.429553
15	15	15	15	2026-07-22	08:00:00	Nhìn mờ, đau mắt	Tăng nhãn áp	Completed	2026-08-17 00:38:09.429553
16	16	16	16	2026-07-22	09:00:00	Cận thị tiến triển	Cận thị nặng	Scheduled	2026-08-17 00:38:09.429553
17	17	1	1	2026-07-23	10:00:00	Tức ngực, khó thở	Suy tim	Completed	2026-08-17 00:38:09.429553
18	18	2	2	2026-07-23	11:00:00	Huyết áp cao	Tăng huyết áp độ 2	Scheduled	2026-08-17 00:38:09.429553
19	19	3	3	2026-07-24	08:30:00	Tay chân tê bì	Hội chứng ống cổ tay	Completed	2026-08-17 00:38:09.429553
20	20	4	4	2026-07-24	09:45:00	Đau nửa đầu	Migraine có aura	Cancelled	2026-08-17 00:38:09.429553
21	21	5	5	2026-07-25	10:30:00	Đau vai gáy	Thoái hóa đốt sống cổ	Completed	2026-08-17 00:38:09.429553
22	22	6	6	2026-07-25	11:30:00	Gãy xương cẳng tay	Gãy xương đã nắn	Scheduled	2026-08-17 00:38:09.429553
23	23	7	7	2026-07-26	08:00:00	Sốt, ho khan	Viêm phổi	Completed	2026-08-17 00:38:09.429553
24	24	8	8	2026-07-26	09:15:00	Tiêu chảy kéo dài	Rối loạn tiêu hóa	Scheduled	2026-08-17 00:38:09.429553
25	25	9	9	2026-07-27	10:00:00	Nổi mề đay	Dị ứng thực phẩm	Completed	2026-08-17 00:38:09.429553
26	26	10	10	2026-07-27	11:00:00	Viêm da cơ địa	Eczema	Scheduled	2026-08-17 00:38:09.429553
27	27	11	11	2026-07-28	08:30:00	Đau bụng dưới	Viêm đại tràng	Completed	2026-08-17 00:38:09.429553
28	28	12	12	2026-07-28	09:45:00	Mệt mỏi, chóng mặt	Thiếu máu	Completed	2026-08-17 00:38:09.429553
29	29	13	13	2026-07-29	10:30:00	Đau rát họng	Viêm họng hạt	Scheduled	2026-08-17 00:38:09.429553
30	30	14	14	2026-07-29	11:15:00	Nghẹt mũi mạn tính	Viêm mũi dị ứng	Completed	2026-08-17 00:38:09.429553
31	1	15	15	2026-07-30	08:00:00	Mờ mắt, nhìn đôi	Đục thủy tinh thể	Scheduled	2026-08-17 00:38:09.429553
32	2	16	16	2026-07-30	09:00:00	Đau mắt đỏ	Viêm kết mạc	Completed	2026-08-17 00:38:09.429553
33	3	1	1	2026-07-31	10:00:00	Tái khám tim mạch	Ổn định	Completed	2026-08-17 00:38:09.429553
34	4	2	2	2026-07-31	11:00:00	Khó thở về đêm	Suy tim đợt cấp	Scheduled	2026-08-17 00:38:09.429553
35	5	3	3	2026-08-01	08:30:00	Đau đầu vùng trán	Viêm xoang trán	Completed	2026-08-17 00:38:09.429553
36	6	4	4	2026-08-01	09:45:00	Chóng mặt sau ngã	Chấn thương sọ não	Cancelled	2026-08-17 00:38:09.429553
37	7	5	5	2026-08-02	10:30:00	Đau khớp gối	Viêm khớp dạng thấp	Completed	2026-08-17 00:38:09.429553
38	8	6	6	2026-08-02	11:30:00	Trật khớp vai	Trật khớp đã nắn	Scheduled	2026-08-17 00:38:09.429553
39	9	7	7	2026-08-03	08:00:00	Sốt, co giật	Sốt cao co giật	Completed	2026-08-17 00:38:09.429553
40	10	8	8	2026-08-03	09:15:00	Nôn trớ nhiều	Trào ngược dạ dày	Scheduled	2026-08-17 00:38:09.429553
41	11	9	9	2026-08-04	10:00:00	Phát ban ở mặt	Rosacea	Completed	2026-08-17 00:38:09.429553
42	12	10	10	2026-08-04	11:00:00	Mụn cóc ở tay	Virus HPV	Scheduled	2026-08-17 00:38:09.429553
43	13	11	11	2026-08-05	08:30:00	Đau thượng vị sau ăn	Viêm dạ dày	Completed	2026-08-17 00:38:09.429553
44	14	12	12	2026-08-05	09:45:00	Khát nước, sụt cân	Đái tháo đường type 1	Scheduled	2026-08-17 00:38:09.429553
45	15	13	13	2026-08-06	10:30:00	Ù tai, đau tai	Viêm tai ngoài	Completed	2026-08-17 00:38:09.429553
46	16	14	14	2026-08-06	11:15:00	Mất khứu giác	Hậu COVID-19	Scheduled	2026-08-17 00:38:09.429553
47	17	15	15	2026-08-07	08:00:00	Đau mắt, nhạy cảm ánh sáng	Loét giác mạc	Completed	2026-08-17 00:38:09.429553
48	18	16	16	2026-08-07	09:00:00	Nhìn mờ, đau đầu	Tăng nhãn áp góc đóng	Scheduled	2026-08-17 00:38:09.429553
49	19	1	1	2026-08-08	10:30:00	Tái khám sau đặt stent	Đã ổn định	Completed	2026-08-17 00:38:09.429553
50	20	2	2	2026-08-08	11:30:00	Hồi hộp, lo âu	Rối loạn nhịp tim	Cancelled	2026-08-17 00:38:09.429553
\.


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (department_id, department_name, description, phone) FROM stdin;
1	Khoa Tim mạch	Chuyên khám và điều trị bệnh lý tim mạch	024-1234567
2	Khoa Thần kinh	Chuyên khám và điều trị bệnh lý thần kinh	024-1234568
3	Khoa Chỉnh hình	Chuyên khám và điều trị bệnh xương khớp	024-1234569
4	Khoa Nhi	Chăm sóc sức khỏe trẻ em từ 0-15 tuổi	024-1234570
5	Khoa Da liễu	Chuyên khám và điều trị bệnh da liễu	024-1234571
6	Khoa Nội tổng quát	Khám và điều trị bệnh nội khoa tổng hợp	024-1234572
7	Khoa Tai Mũi Họng	Khám và điều trị bệnh tai mũi họng	024-1234573
8	Khoa Mắt	Khám và điều trị bệnh mắt	024-1234574
\.


--
-- Data for Name: doctors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.doctors (doctor_id, full_name, specialization, phone, email, department_id, status) FROM stdin;
1	BS. Nguyễn Văn An	Tim mạch can thiệp	0912345001	an.nguyen@bv.com	1	Active
2	BS. Trần Thị Bình	Tim mạch tổng quát	0912345002	binh.tran@bv.com	1	Active
3	BS. Lê Văn Cường	Thần kinh	0912345003	cuong.le@bv.com	2	Active
4	BS. Phạm Thị Dung	Thần kinh nhi	0912345004	dung.pham@bv.com	2	Active
5	BS. Hoàng Văn Em	Chỉnh hình	0912345005	em.hoang@bv.com	3	Active
6	BS. Ngô Thị Phượng	Chỉnh hình cột sống	0912345006	phuong.ngo@bv.com	3	Active
7	BS. Đặng Văn Giang	Nhi tổng quát	0912345007	giang.dang@bv.com	4	Active
8	BS. Vũ Thị Hạnh	Nhi dinh dưỡng	0912345008	hanh.vu@bv.com	4	Active
9	BS. Bùi Văn Ích	Da liễu	0912345009	ich.bui@bv.com	5	Active
10	BS. Đỗ Thị Kha	Da liễu thẩm mỹ	0912345010	kha.do@bv.com	5	Active
11	BS. Lý Văn Lợi	Nội tổng quát	0912345011	loi.ly@bv.com	6	Active
12	BS. Hà Thị Mai	Nội tiết	0912345012	mai.ha@bv.com	6	Active
13	BS. Cao Văn Nghĩa	Tai Mũi Họng	0912345013	nghia.cao@bv.com	7	Active
14	BS. Tăng Thị Oanh	Tai Mũi Họng dị ứng	0912345014	oanh.tang@bv.com	7	Active
15	BS. Dương Văn Phúc	Mắt	0912345015	phuc.duong@bv.com	8	Active
16	BS. Lâm Thị Quyên	Mắt khúc xạ	0912345016	quyen.lam@bv.com	8	Active
\.


--
-- Data for Name: invoice_medicines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_medicines (id, invoice_id, medicine_id, quantity, unit_price, subtotal) FROM stdin;
1	1	1	2	5.00	10.00
2	1	3	1	12.00	12.00
3	2	2	1	7.50	7.50
4	2	4	1	15.00	15.00
5	4	5	2	20.00	40.00
6	4	6	1	10.00	10.00
7	5	7	1	18.00	18.00
8	5	8	2	8.00	16.00
9	6	9	1	25.00	25.00
10	7	11	1	14.00	14.00
11	7	12	2	12.00	24.00
12	8	6	2	10.00	20.00
13	8	1	1	5.00	5.00
14	10	4	1	15.00	15.00
15	10	5	1	20.00	20.00
16	11	2	1	7.50	7.50
17	11	3	1	12.00	12.00
18	12	8	1	8.00	8.00
19	14	7	2	18.00	36.00
20	14	15	1	22.00	22.00
21	15	12	1	12.00	12.00
22	15	14	1	11.00	11.00
23	16	9	1	25.00	25.00
24	16	11	1	14.00	14.00
25	17	10	1	100.00	100.00
26	18	13	1	9.00	9.00
27	18	1	1	5.00	5.00
28	19	2	1	7.50	7.50
29	21	3	2	12.00	24.00
30	21	8	1	8.00	8.00
31	22	4	1	15.00	15.00
32	22	6	2	10.00	20.00
33	23	5	1	20.00	20.00
34	24	1	2	5.00	10.00
35	25	7	1	18.00	18.00
36	25	12	1	12.00	12.00
37	27	9	1	25.00	25.00
38	27	13	1	9.00	9.00
39	28	14	1	11.00	11.00
\.


--
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices (invoice_id, appointment_id, issue_date, examination_fee, medicine_fee, total_amount, payment_status) FROM stdin;
1	1	2026-07-15 08:30:00	50.00	15.00	65.00	Paid
2	2	2026-07-15 10:00:00	50.00	20.00	70.00	Paid
3	4	2026-07-16 10:30:00	60.00	0.00	60.00	Unpaid
4	6	2026-07-17 11:00:00	55.00	12.00	67.00	Paid
5	7	2026-07-18 08:30:00	40.00	25.00	65.00	Paid
6	9	2026-07-19 10:30:00	50.00	10.00	60.00	Unpaid
7	11	2026-07-20 09:00:00	45.00	18.00	63.00	Paid
8	12	2026-07-20 10:15:00	50.00	30.00	80.00	Paid
9	14	2026-07-21 11:45:00	55.00	0.00	55.00	Unpaid
10	15	2026-07-22 08:30:00	60.00	22.00	82.00	Paid
11	17	2026-07-23 10:30:00	50.00	15.00	65.00	Paid
12	19	2026-07-24 09:00:00	55.00	8.00	63.00	Paid
13	21	2026-07-25 10:45:00	45.00	0.00	45.00	Unpaid
14	23	2026-07-26 08:30:00	60.00	28.00	88.00	Paid
15	25	2026-07-27 10:30:00	50.00	14.00	64.00	Paid
16	27	2026-07-28 09:00:00	55.00	20.00	75.00	Paid
17	28	2026-07-28 10:15:00	45.00	10.00	55.00	Paid
18	30	2026-07-29 11:45:00	50.00	12.00	62.00	Unpaid
19	32	2026-07-30 09:30:00	40.00	8.00	48.00	Paid
20	33	2026-07-31 10:30:00	50.00	0.00	50.00	Paid
21	35	2026-08-01 09:00:00	55.00	25.00	80.00	Paid
22	37	2026-08-02 11:00:00	60.00	30.00	90.00	Paid
23	39	2026-08-03 08:30:00	50.00	15.00	65.00	Unpaid
24	41	2026-08-04 10:30:00	55.00	10.00	65.00	Paid
25	43	2026-08-05 09:00:00	45.00	22.00	67.00	Paid
26	45	2026-08-06 10:45:00	50.00	0.00	50.00	Paid
27	47	2026-08-07 08:30:00	60.00	18.00	78.00	Paid
28	49	2026-08-08 11:00:00	50.00	10.00	60.00	Paid
\.


--
-- Data for Name: medicines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medicines (medicine_id, medicine_name, unit, price, stock_quantity, description) FROM stdin;
1	Paracetamol 500mg	Viên	5.00	1000	Giảm đau, hạ sốt
2	Ibuprofen 400mg	Viên	7.50	800	Kháng viêm không steroid
3	Amoxicillin 250mg	Viên nang	12.00	500	Kháng sinh nhóm penicillin
4	Lisinopril 10mg	Viên	15.00	300	Thuốc hạ áp (ACEI)
5	Atorvastatin 20mg	Viên	20.00	400	Thuốc giảm cholesterol
6	Metformin 500mg	Viên	10.00	600	Thuốc hạ đường huyết
7	Omeprazole 20mg	Viên nang	18.00	350	Ức chế bơm proton, trị trào ngược
8	Cetirizine 10mg	Viên	8.00	700	Kháng histamin, trị dị ứng
9	Azithromycin 500mg	Viên	25.00	200	Kháng sinh macrolid
10	Insulin Glargine	Lọ	100.00	50	Insulin tác dụng kéo dài
11	Losartan 50mg	Viên	14.00	250	Thuốc hạ áp (ARB)
12	Salbutamol 2.5mg	Viên	12.00	300	Thuốc giãn phế quản
13	Prednisolone 5mg	Viên	9.00	400	Corticosteroid kháng viêm
14	Furosemide 40mg	Viên	11.00	350	Thuốc lợi tiểu
15	Ciprofloxacin 500mg	Viên	22.00	150	Kháng sinh quinolon
\.


--
-- Data for Name: patients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patients (patient_id, full_name, date_of_birth, gender, phone, email, address, created_at) FROM stdin;
1	Nguyễn Thị Hoa	1990-05-15	Nữ	0901234001	hoa.nguyen@email.com	12 Lê Lợi, Hà Nội	2026-08-17 00:38:09.429553
2	Trần Văn Bình	1985-08-22	Nam	0901234002	binh.tran@email.com	34 Nguyễn Trãi, HCM	2026-08-17 00:38:09.429553
3	Lê Thị Cúc	2000-12-01	Nữ	0901234003	cuc.le@email.com	56 Trần Hưng Đạo, Đà Nẵng	2026-08-17 00:38:09.429553
4	Phạm Văn Đức	1978-03-10	Nam	0901234004	duc.pham@email.com	78 Hai Bà Trưng, Hải Phòng	2026-08-17 00:38:09.429553
5	Hoàng Thị Em	1995-07-19	Nữ	0901234005	em.hoang@email.com	90 Ngô Quyền, Cần Thơ	2026-08-17 00:38:09.429553
6	Ngô Văn Phúc	1982-11-30	Nam	0901234006	phuc.ngo@email.com	12 Trần Phú, Huế	2026-08-17 00:38:09.429553
7	Đặng Thị Giang	2005-02-14	Nữ	0901234007	giang.dang@email.com	34 Lý Tự Trọng, Nha Trang	2026-08-17 00:38:09.429553
8	Vũ Văn Hùng	1970-06-25	Nam	0901234008	hung.vu@email.com	56 Nguyễn Huệ, Vũng Tàu	2026-08-17 00:38:09.429553
9	Bùi Thị Hương	1992-09-08	Nữ	0901234009	huong.bui@email.com	78 Lê Lai, Quảng Ninh	2026-08-17 00:38:09.429553
10	Đỗ Văn Khánh	1988-04-17	Nam	0901234010	khanh.do@email.com	90 Bà Triệu, Bắc Ninh	2026-08-17 00:38:09.429553
11	Lý Thị Linh	2001-01-20	Nữ	0901234011	linh.ly@email.com	12 Hoàng Diệu, Hà Tĩnh	2026-08-17 00:38:09.429553
12	Hà Văn Minh	1993-10-05	Nam	0901234012	minh.ha@email.com	34 Lê Đại Hành, Khánh Hòa	2026-08-17 00:38:09.429553
13	Cao Thị Ngọc	1980-12-12	Nữ	0901234013	ngoc.cao@email.com	56 Nguyễn Văn Linh, Bình Dương	2026-08-17 00:38:09.429553
14	Tăng Văn Phát	1998-07-07	Nam	0901234014	phat.tang@email.com	78 Lê Văn Sỹ, Đồng Nai	2026-08-17 00:38:09.429553
15	Dương Thị Quyên	2008-03-03	Nữ	0901234015	quyen.duong@email.com	90 Trần Quốc Thảo, Bà Rịa	2026-08-17 00:38:09.429553
16	Lâm Văn Sơn	1986-09-12	Nam	0901234016	son.lam@email.com	12 Nguyễn Thị Minh Khai, An Giang	2026-08-17 00:38:09.429553
17	Ngô Thị Thảo	1991-11-21	Nữ	0901234017	thao.ngo@email.com	34 Lý Thường Kiệt, Kiên Giang	2026-08-17 00:38:09.429553
18	Trịnh Văn Toàn	1975-04-18	Nam	0901234018	toan.trinh@email.com	56 Điện Biên Phủ, Sóc Trăng	2026-08-17 00:38:09.429553
19	Võ Thị Uyên	2002-07-30	Nữ	0901234019	uyen.vo@email.com	78 Lê Quý Đôn, Cà Mau	2026-08-17 00:38:09.429553
20	Bạch Văn Vinh	1983-12-05	Nam	0901234020	vinh.bach@email.com	90 Hùng Vương, Đắk Lắk	2026-08-17 00:38:09.429553
21	Lưu Thị Xuân	1996-06-14	Nữ	0901234021	xuan.luu@email.com	12 Nguyễn Đình Chiểu, Lâm Đồng	2026-08-17 00:38:09.429553
22	Mai Văn Yên	2000-08-28	Nam	0901234022	yen.mai@email.com	34 Phan Đình Phùng, Quảng Trị	2026-08-17 00:38:09.429553
23	Đoàn Thị Ái	1989-02-19	Nữ	0901234023	ai.doan@email.com	56 Trần Bình Trọng, Bến Tre	2026-08-17 00:38:09.429553
24	Lê Văn Bảo	1994-05-07	Nam	0901234024	bao.le@email.com	78 Ngô Gia Tự, Hải Dương	2026-08-17 00:38:09.429553
25	Phan Thị Cẩm	2004-09-16	Nữ	0901234025	cam.phan@email.com	90 Trần Hưng Đạo, Vĩnh Phúc	2026-08-17 00:38:09.429553
26	Hoàng Văn Dũng	1981-03-25	Nam	0901234026	dung.hoang@email.com	12 Nguyễn Thái Học, Phú Thọ	2026-08-17 00:38:09.429553
27	Nguyễn Thị Phương	1999-10-10	Nữ	0901234027	phuong.nguyen@email.com	34 Bạch Đằng, Ninh Bình	2026-08-17 00:38:09.429553
28	Trần Văn Gia	2007-01-02	Nam	0901234028	gia.tran@email.com	56 Lê Hồng Phong, Thái Bình	2026-08-17 00:38:09.429553
29	Lê Thị Hồng	1993-06-26	Nữ	0901234029	hong.le@email.com	78 Đinh Tiên Hoàng, Nam Định	2026-08-17 00:38:09.429553
30	Phạm Văn Kỳ	1985-11-11	Nam	0901234030	ky.pham@email.com	90 Quang Trung, Hưng Yên	2026-08-17 00:38:09.429553
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rooms (room_id, room_number, room_type, department_id, status) FROM stdin;
1	P101	Phòng khám tim mạch	1	Available
2	P102	Phòng siêu âm tim	1	Available
3	P201	Phòng khám thần kinh	2	Available
4	P202	Phòng điện não	2	Available
5	P301	Phòng khám chỉnh hình	3	Available
6	P302	Phòng tập phục hồi	3	Available
7	P401	Phòng khám nhi	4	Available
8	P402	Phòng tiêm chủng	4	Available
9	P501	Phòng khám da liễu	5	Available
10	P502	Phòng điều trị laser	5	Available
11	P601	Phòng khám nội	6	Available
12	P602	Phòng nội soi	6	Available
13	P701	Phòng khám TMH	7	Available
14	P702	Phòng nội soi tai mũi họng	7	Available
15	P801	Phòng khám mắt	8	Available
16	P802	Phòng đo thị lực	8	Available
\.


--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_appointment_id_seq', 50, true);


--
-- Name: departments_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_department_id_seq', 8, true);


--
-- Name: doctors_doctor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.doctors_doctor_id_seq', 16, true);


--
-- Name: invoice_medicines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_medicines_id_seq', 39, true);


--
-- Name: invoices_invoice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoices_invoice_id_seq', 28, true);


--
-- Name: medicines_medicine_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medicines_medicine_id_seq', 15, true);


--
-- Name: patients_patient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.patients_patient_id_seq', 30, true);


--
-- Name: rooms_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rooms_room_id_seq', 16, true);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (appointment_id);


--
-- Name: departments departments_department_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_department_name_key UNIQUE (department_name);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (department_id);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (doctor_id);


--
-- Name: invoice_medicines invoice_medicines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_medicines
    ADD CONSTRAINT invoice_medicines_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_appointment_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_appointment_id_key UNIQUE (appointment_id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id);


--
-- Name: medicines medicines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicines
    ADD CONSTRAINT medicines_pkey PRIMARY KEY (medicine_id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (patient_id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (room_id);


--
-- Name: rooms rooms_room_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_room_number_key UNIQUE (room_number);


--
-- Name: appointments fk_appt_doctor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appt_doctor FOREIGN KEY (doctor_id) REFERENCES public.doctors(doctor_id);


--
-- Name: appointments fk_appt_patient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appt_patient FOREIGN KEY (patient_id) REFERENCES public.patients(patient_id);


--
-- Name: appointments fk_appt_room; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appt_room FOREIGN KEY (room_id) REFERENCES public.rooms(room_id);


--
-- Name: doctors fk_doctor_dept; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT fk_doctor_dept FOREIGN KEY (department_id) REFERENCES public.departments(department_id);


--
-- Name: invoice_medicines fk_im_invoice; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_medicines
    ADD CONSTRAINT fk_im_invoice FOREIGN KEY (invoice_id) REFERENCES public.invoices(invoice_id);


--
-- Name: invoice_medicines fk_im_medicine; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_medicines
    ADD CONSTRAINT fk_im_medicine FOREIGN KEY (medicine_id) REFERENCES public.medicines(medicine_id);


--
-- Name: invoices fk_invoice_appt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoice_appt FOREIGN KEY (appointment_id) REFERENCES public.appointments(appointment_id);


--
-- Name: rooms fk_room_dept; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fk_room_dept FOREIGN KEY (department_id) REFERENCES public.departments(department_id);


--
-- PostgreSQL database dump complete
--

\unrestrict gMOkOVw60OCwDnlSerQh0doQvB1TKwAbhmpWaMUbrYqWETuTmrMM40947mU2fjW

