spring.application.name=hospitalProject
# CẤU HÌNH SERVER

server.port=${PORT:8080}

# CẤU HÌNH KẾT NỐI DATABASE

spring.datasource.url=${DB_URL}

# Tên đăng nhập
spring.datasource.username=${DB_USER}

# Mật khẩu (nhập đúng mật khẩu đã đặt khi cài MySQL)
spring.datasource.password=${DB_PASSWORD}

# Driver class (MySQL 8 dùng driver này)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
