spring.application.name=hospitalProject
# CẤU HÌNH SERVER

server.port=${PORT:8080}

# CẤU HÌNH KẾT NỐI DATABASE

spring.datasource.url=${DB_URL}

# Tên đăng nhập
spring.datasource.username=${DB_USER}

# Mật khẩu (nhập đúng mật khẩu đã đặt khi cài PostgreSQL - nếu test local)
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver
